package droolsexample

// list any import classes here.
import drools.ItemCity;
import java.math.BigDecimal;

// declare any global variables here
dialect "java"
rule "hangzhou tourism Item"

   when
      item : ItemCity (purchaseCity == ItemCity.City.HANGZHOU,
                       typeofItem == ItemCity.Type.TOURISM)

   then
      BigDecimal tax = new BigDecimal(0.0);
      item.setLocalTax(tax.multiply(item.getSellPrice()));
end

rule "hangzhou leisure Item"

   when
      item : ItemCity(purchaseCity == ItemCity.City.HANGZHOU,
                      typeofItem == ItemCity.Type.LEISURE)

   then
      BigDecimal tax = new BigDecimal(2.0);
      item.setLocalTax(tax.multiply(item.getSellPrice()));
end